### ISSUE TITLE
[log] Tracker

### ISSUE THREAD

**Issue by at15** [dyweb/gommon#17]
Not scheduled

- [ ] we can't config third party library that is using the log package 
   - this is allowed in Java land, i.e. solr's admin page allow you to config all the package's logging level on the fly)
   - maybe the logger should register itself to a singleton 

Working

- [ ] v2 with better support for field and performance #28 
  - survey for zap, zerolog, nanolog #26 

Finished 

- [x] #16 set color is not supported in formatter interface, so does time format
- [x] #22 first class support for package, allow config log level for individual log entry
- [x] #3 pkg filter should also be considered

**Comment by at15** [comment]
we have log entries registered in logger, the problem is, each library use their own logger instance, unless they all use a `DefaultLogger` or make their logger public, there is no way to control their logging

**Comment by at15** [comment]
fixed in #90
